def create_setup_py() -> str: ...
def login_server_finish_py(client_request_finish: str, login_state: str) -> str: ...
def login_server_py(
    setup: str, password_file: str, client_request: str, credential_id: str
) -> tuple[str, str]: ...
def register_client_finish_py(
    client_register_state: str, password: str, server_message: str
) -> str: ...
def register_client_py(password: str) -> tuple[str, str]: ...
def register_server_finish_py(client_request_finish: str) -> str: ...
def register_server_py(setup: str, client_request: str, credential_id: str) -> str: ...
