[package]
name = "opaquepy"
version = "0.3.7"
edition = "2021"

[lib]
name = "opaquepy"
crate-type = ["cdylib"]

[dependencies]
opaque-borink = { path = "../opaque-borink" }

[dependencies.pyo3]
version = "0.21"
features = ["extension-module"]