[package]
name = "opaquepy"
version = "0.6.0"
edition = "2021"

[lib]
name = "opaquepy"
crate-type = ["cdylib"]

[dependencies]
opaque-borink = { path = "../opaque-borink" }

[dependencies.pyo3]
version = "0.23.3"
features = ["extension-module"]