[package]
name = "opaquepy"
version = "0.3.5"
edition = "2021"

[lib]
name = "opaquepy"
crate-type = ["cdylib"]

[dependencies]
opaquebind = { path = "../opaquebind" }

[dependencies.pyo3]
version = "0.19.2"
features = ["extension-module"]