[package]
name = "opaquepy"
version = "0.2.1"
edition = "2021"

[lib]
name = "_opaquepy"
crate-type = ["cdylib"]

[dependencies]
opaquebind = { path = "../opaquebind" }

[dependencies.pyo3]
version = "0.17.1"
features = ["extension-module"]

[package.metadata.maturin]
python-source = "python"