[project]
name = "opaquepy"
version = "0.2.1"
description = "Python bindings for opaque-ke."
readme = "README.md"
requires-python = ">=3.9, <3.11"
license = {text = "Apache-2.0"}
authors = [
    {email = "75669206+tiptenbrink@users.noreply.github.com"},
    {name = "Tip ten Brink"}
]

[tool.maturin]
python-source = "python"

[tool.poetry]
name = "opaquepy"
version = "0.2.1"
description = "Python bindings for opaque-ke."
authors = ["Tip ten Brink <75669206+tiptenbrink@users.noreply.github.com>"]
license = "Apache-2"

[tool.poetry.dependencies]
python = ">= 3.9, <3.11"

[tool.poetry.dev-dependencies]
maturin = "^0.13"
pytest = "^7.1.3"

[build-system]
requires = ["maturin >= 0.13, < 0.14"]
build-backend ="maturin"
