[project]
name = "opaquepy"
version = "0.3.3"
description = "Python bindings for opaque-ke."
readme = "README.md"
requires-python = ">=3.9, <3.12"
license = {text = "Apache-2.0"}
authors = [
    {email = "75669206+tiptenbrink@users.noreply.github.com"},
    {name = "Tip ten Brink"}
]

[tool.maturin]
python-source = "python"

[tool.poetry]
name = "opaquepy"
version = "0.3.3"
description = "Python bindings for opaque-ke."
authors = ["Tip ten Brink <75669206+tiptenbrink@users.noreply.github.com>"]
license = "Apache-2"

[tool.poetry.dependencies]
python = ">= 3.9, <3.12"

[tool.poetry.dev-dependencies]
maturin = "^0.13"
pytest = "^7.1.3"
mypy = "^0.991"
black = "^22.8.0"

[tool.mypy]
python_version = "3.9"
strict = true
files = ["python"]

[build-system]
requires = ["maturin >= 0.13, < 0.14"]
build-backend ="maturin"
