[package]
name = "opaquebind"
version = "0.2.0"
edition = "2021"
authors = ["Tip ten Brink <75669206+tiptenbrink@users.noreply.github.com>"]
license = "Apache-2.0"
keywords = ["opaque", "passwords", "authentication", "serialization"]
readme = "README.md"
repository = "https://github.com/tiptenbrink/opaquebind/tree/main/opaquebind"
description = "Simple interface to opaque-ke and core library for Python and WASM bindings."

[lib]
name = "opaquebind"

[dependencies]
opaque-ke = { version = "1.2.0", features = ["slow-hash"] }
curve25519-dalek = { version = "3", default-features = false }
sha2 = "0.9"
rand = { version = "0.8", default-features = false, features = ["getrandom"] }
digest = "0.9"
base64 = "0.13.0"
argon2 = "0.3"